name: CHANGELOG generator
description: Generate CHANGELOG automatically
author: rot1024
runs:
  using: node16
  main: dist/main.js
branding:
 icon: file-text
 color: purple
inputs:
  version:
    description: A new version, "patch", "minor", or "major".
    required: false
    default: minor
  versionPrefix:
    description: If "add" is specified, v will be prepended to the version as a tag name. "remove" will remove the prefix from the version.
    required: false
  titleVersionPrefix:
    description: If "add" is specified, v will be prepended to the version as the title on the CHANGELOG. "remove" will remove the prefix from the version.
    required: false
  date:
    description: 'Release date. Default: current local time'
    required: false
  repo:
    description: Repository name (owner/name) or URL used in CHANGELOG as the link destination for commits and pull requests.
    required: false
  latest:
    description: If true, generates CHANGELOG_latest.md also. You can also specify a file name.
    required: false
  output:
    description: CHANGELOG.md file path
    required: false
    default: CHANGELOG.md
  config:
    description: Config JSON file path
    required: false
    default: .github/changelog.json
outputs:
  changelog:
    description: The latest CHANGELOG
  version:
    description: The new version
  date:
    description: Date of the new version
  prevVersion:
    description: The previous version
  newChangelog:
    description: The new CHANGELOG
  oldChangelog:
    description: The old CHANGELOG
