name: CHANGELOG generator
description: Generate CHANGELOG automatically
author: rot1024
runs:
  using: node16
  main: dist/main.js
branding:
 icon: file-text
 color: purple
inputs:
  version:
    description: A new version, "patch", "minor", or "major".
    required: false
    default: minor
  versionAsIs:
    description: Use the specified version even if "v" prefix is missing in it.
    required: false
  date:
    description: 'Release date. Default: current local time'
    required: false
  url:
    description: Repository URL used in CHANGELOG as the link destination for commits and pull requests.
    required: false
  latest:
    description: If true, generates CHANGELOG_latest.md also. You can also specify a file name.
    required: false
  output:
    description: CHANGELOG.md file path
    required: false
    default: CHANGELOG.md
  config:
    description: Config JSON file path
    required: false
    default: .github/changelog.json
outputs:
  changelog:
    description: The latest CHANGELOG
  version:
    description: The new version
  prevVersion:
    description: The previous version
  newChangelog:
    description: The new CHANGELOG
  oldChangelog:
    description: The old CHANGELOG
