name: CHANGELOG generator
description: Generate CHANGELOG automatically
author: rot1024
runs:
  using: node16
  main: dist/index.js
branding:
 icon: file-text
 color: purple
inputs:
  version:
    description: A new version ("vX.X.X"), "patch", "minor", "major", "prepatch", "preminor", "premajor", or "prerelease". Default automatically detects a new version from commits.
    required: false
  date:
    description: 'Release date. Default: current local time'
    required: false
  repo:
    description: Repository name (owner/name) or URL used in CHANGELOG as the link destination for commits and pull requests.
    required: false
  latest:
    description: If true, generates CHANGELOG_latest.md also. You can also specify a file name.
    required: false
  output:
    description: CHANGELOG.md file path
    required: false
    default: CHANGELOG.md
  noEmit:
    description: If true, any files will not be emitted. The result is only available from the outputs.
    required: false
  config:
    description: Config JSON file path
    required: false
    default: .github/changelog.json
outputs:
  changelog:
    description: The latest CHANGELOG
  version:
    description: The new version
  date:
    description: Date of the new version
  prevVersion:
    description: The previous version
  newChangelog:
    description: The new CHANGELOG
  oldChangelog:
    description: The old CHANGELOG
