name: CHANGELOG generator
description: Generate CHANGELOG automatically
author: rot1024
runs:
  using: node16
  main: main.mjs
branding:
 icon: file-text
 color: purple
inputs:
  version:
    description: A new version, "patch", "minor", or "major".
    required: false
    default: minor
  date:
    description: Release date
    required: false
  latest:
    description: If true, generates CHANGELOG_latest.md also.
    required: false
  output:
    description: CHANGELOG.md file path
    required: false
    default: CHANGELOG.md
  config:
    description: config file path
    required: false
    default: .github/changelog.json
outputs:
  changelog:
    description: The latest CHANGELOG
  version:
    description: The new version
  prevVersion:
    description: The previous version
  newChangelog:
    description: The new CHANGELOG
  oldChangelog:
    description: The old CHANGELOG
