on:
  push:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: changelog
        uses: ./
      - name: Print version
        run: echo "$PREV_VERSION -> $VERSION"
        env:
          VERSION: ${{ steps.changelog.output.version }}
          PREV_VERSION: ${{ steps.changelog.output.prev_version }}
      - name: Print CHANGELOG
        run: echo $CHANGELOG
        env:
          CHANGELOG: ${{ steps.changelog.output.changelog }}
      - name: Print CHANGELOG file
        run: cat CHANGELOG.md
